name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:

  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_USERNAME: Waka(bot)
          COMMIT_MESSAGE: ':hammer: Waka: Update dev metrics'
          SHOW_PROFILE_VIEWS: False
          SHOW_TITLE: True
          SHOW_PROJECTS: False
          SHOW_UPDATED_DATE: True
          SHOW_LINES_OF_CODE: True
          SHOW_DAYS_OF_WEEK: False
          SHOW_TIMEZONE: True
          TIME_RANGE: all_time

